apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cronguard-db
  name: cronguard-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cronguard-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cronguard-db
    spec:
      containers:
        - image: andreaswendlandt/cronguard-db:latest
          name: cronguard-db
          resources: {}
      restartPolicy: Always
status: {}
