apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cronguard-daemon
  name: cronguard-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cronguard-daemon
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cronguard-daemon
    spec:
      containers:
        - image: andreaswendlandt/cronguard-daemon:latest
          name: cronguard-daemon
          resources: {}
          volumeMounts:
            - mountPath: /var/log
              name: cronguard-daemon-claim0
      restartPolicy: Always
      volumes:
        - name: cronguard-daemon-claim0
          persistentVolumeClaim:
            claimName: cronguard-daemon-claim0
status: {}
