apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cronguard-web
  name: cronguard-web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cronguard-web
  template:
    metadata:
      labels:
        io.kompose.service: cronguard-web
    spec:
      containers:
        - image: andreaswendlandt/cronguard-web:latest
          name: cronguard-web
          ports:
            - containerPort: 80
      restartPolicy: Always
