apiVersion: v1
kind: Service
metadata:
  labels:
    cronguard.service: cronguard-web
  name: cronguard-web
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    cronguard.service: cronguard-web
