apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cronguard.service: cronguard-db
  name: cronguard-db
spec:
  replicas: 1
  selector:
    matchLabels:
      cronguard.service: cronguard-db
  template:
    metadata:
      labels:
        cronguard.service: cronguard-db
    spec:
      containers:
        - image: andreaswendlandt/cronguard-db:latest
          name: cronguard-db
      restartPolicy: Always
