apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cronguard.service: cronguard-daemon
  name: cronguard-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      cronguard.service: cronguard-daemon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        cronguard.service: cronguard-daemon
    spec:
      containers:
        - image: andreaswendlandt/cronguard-daemon:latest
          name: cronguard-daemon
          volumeMounts:
            - name: cronguardlog
              mountPath: /var/log
      restartPolicy: Always
      volumes:
        - name: cronguardlog
          hostPath:
            path: /tmp/log
